BoxLayout:
    orientation: 'vertical'
    Label:
        text: "Convert Miles to Kilometres"
        font_size: 32
        size_hint_y: 0.2

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: 0.2

        TextInput:
            id: input_miles
            text: "0"
            font_size: 48
            multiline: False
            on_text: app.handle_convert()

        BoxLayout:
            orientation: "vertical"
            size_hint_x: 0.25

            Button:
                text: "Up"
                on_press: app.handle_increment(1)

            Button:
                text: "Down"
                on_press: app.handle_increment(-1)

    Button:
        text: "Convert miles to km"
        size_hint_y: 0.2
        on_press: app.handle_convert()

    Label:
        text: app.output_km
        font_size: 48
        color: (1, 1, 0, 1)
        size_hint_y: 0.4